### ISSUE TITLE
Cannot install OpenMDAO 0.10.3.2

### ISSUE THREAD

**Issue by crobarcro** [FUSED-Wind/fusedwind#83]
I would like to have a go using FUSED-Wind but am finding it impossible to install OpenMDAO 0.10.3.2 (which seems to now be a rather ancient version). On Ubuntu 18.04 if I follow the instructions, i.e.:

```
cd git
git clone https://github.com/OpenMDAO/OpenMDAO-Framework.git
git checkout 0.10.3.2
```

Then run 
```
python go-openmdao-dev.py
```

I first got an error like this:

```
$ python ~/src/OpenMDAO-Framework-git/go-openmdao-dev.py
New python executable in /home/rcrozier/src/OpenMDAO-Framework-git/devenv/bin/python
Installing setuptools............done.
Installing pip.............done.
Patching site.py...
  found '                paths.append(lib64_path)\n'
    new '                paths.insert(0, lib64_path)\n'
Traceback (most recent call last):
  File "/home/rcrozier/src/OpenMDAO-Framework-git/go-openmdao-dev.py", line 3074, in <module>
    main()
  File "/home/rcrozier/src/OpenMDAO-Framework-git/go-openmdao-dev.py", line 983, in main
    after_install(options, home_dir)
  File "/home/rcrozier/src/OpenMDAO-Framework-git/go-openmdao-dev.py", line 2246, in after_install
    __import__(pkg)
  File "/home/rcrozier/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/rcrozier/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 59, in <module>
    from . import numeric
  File "/home/rcrozier/.local/lib/python2.7/site-packages/numpy/core/numeric.py", line 3093, in <module>
    from . import fromnumeric
  File "/home/rcrozier/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 17, in <module>
    from . import _methods
  File "/home/rcrozier/.local/lib/python2.7/site-packages/numpy/core/_methods.py", line 158, in <module>
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'
```
I realised this was because the specified version of numpy is too new, so I tried modifying go-openmdao-dev.py so that it specified `numpy==1.15.4`, but I then get an error like:

```
$ python go-openmdao-dev.py 
New python executable in devenv/bin/python
Installing setuptools............done.
Installing pip.............done.
Patching site.py...
  found '                paths.append(lib64_path)\n'
    new '                paths.insert(0, lib64_path)\n'
ERROR: the following prerequisites could not be imported: ['numpy==1.15.4', 'scipy>=0.11.0', 'scipy>=0.11.0'].
These must be installed in the system level python before installing OpenMDAO.
To run a limited version of OpenMDAO without the prerequisites, try 'python go-openmdao-dev.py --noprereqs'
```

Can you advise on how to work around this so I can install FUSED-Wind?

**Comment by YuhaoLi2333** [comment]
Hi, did you fix the problem?
I get the similar error information: 
```
ERROR: the following prerequisites could not be imported: ['numpy', 'scipy>=0.11.0', 'scipy>=0.11.0'].
These must be installed in the system level python before installing OpenMDAO.
To run a limited version of OpenMDAO without the prerequisites, try 'python go-openmdao-0.10.3.2.py --noprereqs'
```
But I have installed numpy(1.16.5) and scipy(0.17.1).

**Comment by crobarcro** [comment]
No, I gave up, this project seem to be abandoned. I converted some stuff I was interested in to Matlab.

**Comment by fzahle** [comment]
hi all,
indeed this project is no longer being developed, since it depends on a now legacy version of OpenMDAO. Depending on what you want to use the code for, there are related projects done by DTU and NREL that I can point you to. Let me know what your uses of it are.

**Comment by michaelXDzhang** [comment]
Hi   Zahle,
Yes, I installed a old version just for learning , but the fusedwind is  worth to keep also, but it still depending on openmdao old version,  luckly the Topfarm is updated to 2.x
Regards,
.
Michael

发件人: Frederik Zahle <notifications@github.com>
发送时间: 2019年10月8日 21:55
收件人: FUSED-Wind/fusedwind <fusedwind@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [FUSED-Wind/fusedwind] Cannot install OpenMDAO 0.10.3.2 (#83)


hi all,
indeed this project is no longer being developed, since it depends on a now legacy version of OpenMDAO. Depending on what you want to use the code for, there are related projects done by DTU and NREL that I can point you to. Let me know what your uses of it are.

**Comment by michaelXDzhang** [comment]
Hi
I installed it 2 years ago, it must be lower lever version, some of pkgs need build from source because they are too old, openmdao must be 0.1.13 I remember, python 2.7….
Hopefully helpful,
Michael zhang

发件人: YuhaoLi2333 <notifications@github.com>
发送时间: 2019年10月8日 21:43
收件人: FUSED-Wind/fusedwind <fusedwind@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [FUSED-Wind/fusedwind] Cannot install OpenMDAO 0.10.3.2 (#83)


Hi, did you fix the problem?
I get the similar error information:

ERROR: the following prerequisites could not be imported: ['numpy', 'scipy>=0.11.0', 'scipy>=0.11.0'].

These must be installed in the system level python before installing OpenMDAO.

To run a limited version of OpenMDAO without the prerequisites, try 'python go-openmdao-0.10.3.2.py --noprereqs'

But I have installed numpy(1.16.5) and scipy(0.17.1).
